services:
  main-server:
    build:
      context: .
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/graphql?schema=public
    restart: always
    ports:
      - 3000:3000
      
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=graphql
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always